# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.runs/synth_1/led.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 2
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu2cg-sfvc784-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -sv C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/led.sv
read_verilog -library xil_defaultlib -sv {
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std_simple_edge_detector.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oai21.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_sjkff.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_inv.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_7seg_decode.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_slatch_clr.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_fifo_sync.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_oh_mux5.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_oh_mux12.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_and2.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_aoi21.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_fifo_async.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_mux2.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_reg1.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oa222.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_xnor2.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_or4.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_abs.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_clockmux_sync.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_nand4.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_dff.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_aoi32.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_sdffqn.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_ao21.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_clockmux4.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_bin2onehot.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oa32.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oai32.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_par2ser.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_stff.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_dffsq.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_xor4.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_oh_mux2.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_ao222.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_barrel_shifter.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_ao32.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_both2pulse.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_ao311.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_delay.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oai311.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oa31.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_latq.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_jkff.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_pwr_isohi.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_rsync.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_ser2par.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_rise2pulse.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std_gf_edge_detector.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oa211.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std_gf_univibrator.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_ao211.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_aoi221.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_dffrqn.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_oh_mux3.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_clockgate.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_aoi311.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_csa62.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_mux4.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_or2.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_xor3.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_ao33.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_nmos.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oai22.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_muxi4.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_regfile.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_nor2.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_edgedetect.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_stffe.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_nand2.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_sdffsq.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_oh_mux.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_clockmux2.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_arbiter.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_ssrff.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_iobuf.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_lat0_reg.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oai33.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_sdffq.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_oh_mux8.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/advanced_reset/reset.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_sdff.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_stretcher.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_ram_dp.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_counter.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_dffe.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_gray2bin.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_dffqn.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_csa42.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_xnor3.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_latch.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_csa92.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_aoi31.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_jkffe.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_tff.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_ao22.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_mux.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_sdffsqn.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/cfg_generic.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oa33.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_crc32_64b.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oai31.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_sdffrq.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_oh_mux9.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_add.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_clockdiv.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_pulse2pulse.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_clockor.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_latnq.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_bitreverse.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_8b10b_encode.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_nor4.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oai222.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_pmos.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_datagate.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_delay_sel.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_lat1_reg.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_dffrq.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_muxi2.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_dsync.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oa22.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_oh_mux6.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_and3.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_aoi22.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_parity.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_buffer.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_8b10b_decode.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_mux3.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oa221.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_pll.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_dffeas.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_iddr.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_aoi33.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_ssrffe.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_nand3.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_nor3.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oai221.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_ram_sp.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_oddr.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_pwr_isolo.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_dffsqn.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_dffnq.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_edgealign.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_standby.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_and4.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_muxi3.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_csa32.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_bin2gray.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_debouncer.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_fall2pulse.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oa21.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_oh_mux7.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_timer.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_tristate.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_xnor4.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_ao221.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_ao31.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_srff.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_pwr_gate.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_tffe.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_srffe.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/advanced_reset/internal_reset_n.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_dffea.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_aoi211.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_aoi222.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_crc32_8b.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_io_reg_ena.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_sdffe.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/advanced_reset/advanced_reset_n.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_clockmux.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/mux/std_oh_mux4.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_pwr_buf.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_oa311.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_edge2pulse.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_latch_clr.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_reg0.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_xor2.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/std/std_crc.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_sdffrqn.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/comb_gates/std_or3.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_sjkffe.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_slatch.sv
  C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/sources_1/new/FPGA_STD_LIBRARY/triggers/std_dffq.sv
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/constrs_1/new/led.xdc
set_property used_in_implementation false [get_files C:/Users/admin/Documents/xilinx/xilinx_axu2cgb_board/led/led.srcs/constrs_1/new/led.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top led -part xczu2cg-sfvc784-1-i
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef led.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file led_utilization_synth.rpt -pb led_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
